### PR TITLE
Fixes #6: Fatal error when removing package

### LINKED ISSUE #6: Fatal error when removing package
Installing, then removing the package results in a fatal error:

```
PHP Fatal error:  Class 'Mouf\NodeJsInstaller\NodeJsVersionMatcher' not found in .../vendor/mouf/nodejs-installer/src/NodeJsPlugin.php on line 59
```

Steps to reproduce:

```
composer init
composer require --dev mouf/nodejs-installer
composer install --no-dev
```

Stacktrace:

```
PHP Stack trace:
PHP   1. {main}() /composer.phar:0
PHP   2. require() /composer.phar:25
PHP   3. Composer\Console\Application->run() phar:///composer.phar/bin/composer:43
PHP   4. Symfony\Component\Console\Application->run() phar:///composer.phar/src/Composer/Console/Application.php:84
PHP   5. Composer\Console\Application->doRun() phar:///composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:126
PHP   6. Symfony\Component\Console\Application->doRun() phar:///composer.phar/src/Composer/Console/Application.php:147
PHP   7. Symfony\Component\Console\Application->doRunCommand() phar:///composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:195
PHP   8. Symfony\Component\Console\Command\Command->run() phar:///composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:874
PHP   9. Composer\Command\InstallCommand->execute() phar:///composer.phar/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
PHP  10. Composer\Installer->run() phar:///composer.phar/src/Composer/Command/InstallCommand.php:131
PHP  11. Composer\Autoload\AutoloadGenerator->dump() phar:///composer.phar/src/Composer/Installer.php:330
PHP  12. Composer\EventDispatcher\EventDispatcher->dispatchScript() phar:///composer.phar/src/Composer/Autoload/AutoloadGenerator.php:252
PHP  13. Composer\EventDispatcher\EventDispatcher->doDispatch() phar:///composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:91
PHP  14. call_user_func:{phar:///composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:151}() phar:///composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:151
PHP  15. Mouf\NodeJsInstaller\NodeJsPlugin->postAutoloadDump() phar:///composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:151
```

### PR DESCRIPTION
**Pull request by ghost**
This commit fixes issue #6 by returning from the hook when the package is already uninstalled without doing anything.

### CODE REVIEW

**Comment by ghost** [comment]
Unit tests don't cover everything, will do manual testing and resubmit.

**Comment by moufmouf** [comment]
Yes, unit tests are kind of hard on this project since it is a Composer plugin and it behaves differently depending on the availability of Node globally or not.
Anyway, thanks for the PR and do not hesitate to submit it again once you have manually tested it.

I hope you find node-installer useful!

**Comment by ghost** [comment]
I'm reasonably sure it works now, please test and merge.

**Comment by moufmouf** [comment]
Works great for me. Thanks a lots!

**Pull request merged**
